import AboutLayout from "@/components/about/aboutLayout";
import NavBarLayout from "@/components/common/nav/navBarLayout";
import Head from "next/head";

const About = () => {
    return (
      <>
        <Head>
          <title>E-shop | About </title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
            crossorigin="anonymous"
          ></link>

          <link rel="icon" href="/tabIcon.png" />
        </Head>
        <NavBarLayout />
        <AboutLayout />
      </>
    );
}
 
export default About;